
      integer annee,mois,jour,heure,minute,sec
      double precision 
     $     Tps_CPU,
     $     Viriel,
     $     Erreur_rel_E,
     $     Erreur_rel_M,
     $     Nb_moy_VN_pos_orb_par_pas,
     $     Nb_moy_parcrs_arbre_par_pas,
     $     Nb_moy_test_LC_par_pas,
     $     Nb_moy_rejet_paire_par_pas,
     $     Frac_Pas_Relax,
     $     Frac_SuperRenc_Pi16,
     $     Frac_SuperRenc_Pi8,
     $     Frac_SuperRenc_Pi4,
     $     Frac_SuperRenc_Pi2,
     $     Frac_Coll_P_025,
     $     Frac_Coll_P_05,
     $     Frac_Coll_P_1,
     $     Frac_Coll_P_2,
     $     Frac_Kick_P_025,
     $     Frac_Kick_P_05,
     $     Frac_Kick_P_1,
     $     Frac_Kick_P_2,
     $     Frac_Renc_dR_001,
     $     Frac_Renc_dR_01,
     $     Frac_Renc_dR_05,
     $     Frac_Renc_dR_1

      common /GlobTech_date_heure/
     $     annee,mois,jour,heure,minute,sec

      common /GlobTech_common/
     $     Tps_CPU,
     $     Viriel,
     $     Erreur_rel_E,
     $     Erreur_rel_M,
     $     Nb_moy_VN_pos_orb_par_pas,
     $     Nb_moy_parcrs_arbre_par_pas,
     $     Nb_moy_test_LC_par_pas,
     $     Nb_moy_rejet_paire_par_pas,
     $     Frac_Pas_Relax,
     $     Frac_SuperRenc_Pi16,
     $     Frac_SuperRenc_Pi8,
     $     Frac_SuperRenc_Pi4,
     $     Frac_SuperRenc_Pi2,
     $     Frac_Coll_P_025,
     $     Frac_Coll_P_05,
     $     Frac_Coll_P_1,
     $     Frac_Coll_P_2,
     $     Frac_Kick_P_025,
     $     Frac_Kick_P_05,
     $     Frac_Kick_P_1,
     $     Frac_Kick_P_2,
     $     Frac_Renc_dR_001,
     $     Frac_Renc_dR_01,
     $     Frac_Renc_dR_05,
     $     Frac_Renc_dR_1

